const arrStr = [
  '👌👀👌👀👌👀👌👀👌👀 boa merda boa mERda👌 esta sim é uma ✔ boa 👌👌merda aí👌👌mes 👌 mo👌👌👌 aí✔mesmo ✔✔ ƽe você me permite dizer 💯 eu digo 💯 é disso aí que estou falando bem aí bem aí (refrão: bem aí) mMMMMᎷМ💯 👌👌 👌НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀👀 👀 👌👌Boa merda ',
  'Que merda você disse pra mim, seu putinho? Vou te informar, eu me formei no topo da minha classe de Guerra na Selva, e eu estive envolvido em numerosos ataques secretos contra as FARC, e tenho mais de 300 mortes confirmadas. Eu sou treinado em combate de onça, e sou o caçador mais condecorado em todas as forças armadas brasileiras. Você não é nada pra mim se não mais um alvo. Eu irei destruí-lo com uma precisão jamais vista antes neste planeta, guarde minhas palavras. Você acha que pode se livrar falando essas merdinhas pra mim na internet? Pense melhor, filho da puta. Enquanto falamos, estou contactando meu grupo secreto de espiões pelo Brasil, e o seu IP está sendo rastreado imediatamente, então é melhor se preparar para a avalanche, energúmeno. A avalanche que irá acabar com essa coisinha patética que você chama de vida. Está morto, pirralho. Eu posso estar em qualquer lugar, a qualquer instante, e posso te matar em mais de setecentas maneiras só com as minhas mãos. Não apenas eu sou treinado extensivamente em artes marciais, mas também tenho acesso à todo o arsenal militar do Exército Brasileiro e vou usá-lo para expulsar o seu cuzinho pra fora desse continente, seu beócio. Se apenas você tivesse conhecimento da vingança profana que o seu comentário “espertinho” iria lhe trazer, talvez tivesse ficado calado. Mas você não pôde, e não o fez, e agora irá pagar o preço, seu apedeuta. Eu irei te aniquilar e você ficará dizimado. Estás morto, moleque. ',
  'Meu nome é Van, eu sou um artista, um artista de performance. Eu sou contratado pelas pessoas pra realizar as fantasias delas, as fantasias escuras e profundas. Eu ia ser um artista de cinema, modelando e atuando. Depois de 100 ou 200 audições e pequenos papéis, eu decidi que era o bastante. Então eu entrei pro mundo dos escorts. Os pedidos dos clientes tinham muitos fetiches, então eu decidi virar... um completo ♂Mestre♂ e modifiquei minha casa para se tornar um calabouço.♂Mestre♂do♂Calabouço♂ agora com um calabouço completo na minha casa e está indo bem. Fisting é 300 pratas e normalmente o cara já está dopado pra ficar bem relaxado e eu tenho uma luva de latex bem grande que vai até o meu sovaco e então eu coloco uma luva cirurgica de latex até meu punho e só passo o lubrificante. É um processo longo, você sabe, pra colocar o seu braço inteiro lá, mas é um sentimento intenso para a outra pessoa e eu acho que pra mim também. Você entra em lugares que mesmo sendo físico com sua mão, mas também é mais emocial, é mais psicológico também e ambos acabamos conhecendo o mesmo lugar, é estranho também ao mesmo tempo e eu acho as sessões bem cansativas. Eu não sei, eu me sinto pelado porque eu estou me olhando pela primeira vez, bem, não eu mesmo, mas esse aspecto da minha vida pela primeira vez e tem sido difícil... De 3 a 5 anos já? Eu nunca pensei sobre isso. É meio triste... Eu me sinto meio triste agora, eu não sei porque. '  
]

export function getOneCopy(){
  const random = Math.floor(Math.random()*arrStr.length)
  
  return `${arrStr[random]}`
}

/* todo: news on server https://thenewscc.com.br/*/